version: '3.3'

services:
  game_10:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./sql/event.sql:/docker-entrypoint-initdb.d/event.sql
      - ./sql/event_to_game.sql:/docker-entrypoint-initdb.d/event_to_game.sql
      - ./sql/game.sql:/docker-entrypoint-initdb.d/game.sql
      - ./sql/person.sql:/docker-entrypoint-initdb.d/person.sql
      - ./sql/question.sql:/docker-entrypoint-initdb.d/question.sql
      - ./sql/question_history.sql:/docker-entrypoint-initdb.d/question_history.sql
      - ./sql/session.sql:/docker-entrypoint-initdb.d/session.sql
      - ./sql/transaction.sql:/docker-entrypoint-initdb.d/transaction.sql
      - ./sql/users.sql:/docker-entrypoint-initdb.d/users.sql
  app_game_10:
    restart: always
    build: ./app
    volumes:
      - ./app:/app:rw
    ports:
      - '13454:13452'
    environment:
      HOST: http://localhost
      DB_PASSWORD: postgres
      DB_LOGIN: postgres
      DB_HOST: game_10
      DB_NAME: postgres
      DB_PORT: 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080