version: '3.3'

services:
  db_10:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app_back_10:
    restart: always
    build: ./app
    volumes:
      - ./app:/app:rw
    ports:
      - '13455:13452'
    environment:
      HOST: http://localhost
      DB_PASSWORD: postgres
      DB_LOGIN: postgres
      DB_HOST: db_10
      DB_NAME: postgres
      DB_PORT: 5432
