version: '3.2'

services:
  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
  db_php:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'vk_2022'
      MYSQL_USER: 'vk_2022'
      MYSQL_PASSWORD: 'vk_2022'
      MYSQL_ROOT_PASSWORD: 'vk_2022'
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080